name: Ruff format diagnostic

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  diff:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.1.0
      - run: uv sync
      - name: Show Ruff formatting diff
        shell: pwsh
        run: |
          uv run ruff format .
          git diff
